version: "3"

services:
  app:
    container_name: app
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - PORT=4000
    ports:
      - "4000:4000"
  mongo:
    ports:
      - "27017:27017"
